import {words,shuffle,makeRound,normalize} from './data.js';
import {sentences} from './sentences.js';
const $=s=>document.querySelector(s);const names={spelling:'拼写闯关',sound:'听音辨词',meaning:'词义挑战',syntax:'长难句拆解',adaptive:'自适应词汇测试'};
let level=Number(new URLSearchParams(location.search).get('level'))||6;if(level<5||level>9)level=6;
let saved=[];try{saved=JSON.parse(localStorage.getItem('silvia-words')||'[]');if(!Array.isArray(saved))saved=[];saved=saved.filter(w=>words.some(x=>x.word===w))}catch{$('#storage-note').textContent='浏览器存储不可用，本次收藏仅在当前页面保留。'}
let round=[],position=0,score=0,mode='meaning',answered=false,history=[],currentLevel=6,used=new Set(),reviewing=false;
const speechAvailable='speechSynthesis' in window&&'SpeechSynthesisUtterance' in window;
function persist(){try{localStorage.setItem('silvia-words',JSON.stringify(saved))}catch{$('#storage-note').textContent='无法保存到浏览器，本次收藏仅在当前页面保留。'}}
function add(word){if(!saved.includes(word)){saved.push(word);persist();renderSaved()}}
function say(word,slow=false){if(!speechAvailable)return;window.speechSynthesis.cancel();$('#audio-status').textContent='正在播放英语发音…';const u=new SpeechSynthesisUtterance(word);u.lang='en-GB';u.rate=slow?.7:.9;const voices=window.speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='en-GB')||voices.find(v=>v.lang.startsWith('en'))||null;u.onend=()=>{$('#audio-status').textContent='播放完成，可以再次播放或跟读。'};u.onerror=()=>{$('#audio-status').textContent='发音播放失败，请检查设备英语语音、音量及浏览器权限。'};window.speechSynthesis.speak(u)}
function stopAudio(){if(speechAvailable)window.speechSynthesis.cancel()}
function audioButton(word,label='播放发音',slow=false){const b=document.createElement('button');b.type='button';b.className='quiet';b.textContent=label;b.disabled=!speechAvailable;b.onclick=()=>say(word,slow);return b}
function renderSaved(){const node=$('#saved');node.replaceChildren();$('#saved-count').textContent=`(${saved.length})`;$('#review').disabled=!saved.length;if(!saved.length){node.innerHTML='<p class="empty">完成一轮练习，把需要巩固的单词收进这里。</p>';return}for(const key of saved){const w=words.find(w=>w.word===key);const row=document.createElement('div');row.className='saved-word';const details=document.createElement('div');details.innerHTML=`<strong>${w.word}</strong><p>${w.meaning} · ${w.level} 分目标组</p>`;const actions=document.createElement('div');actions.className='saved-actions';actions.append(audioButton(w.word,'听发音'));const remove=document.createElement('button');remove.className='quiet';remove.textContent='移出已掌握';remove.onclick=()=>{saved=saved.filter(s=>s!==key);persist();renderSaved()};actions.append(remove);row.append(details,actions);node.append(row)}}
function renderBands(){const node=$('.bands');node.replaceChildren();for(let n=5;n<=9;n++){const b=document.createElement('button');b.textContent=`${n} 分`;b.setAttribute('aria-pressed',n===level);b.onclick=()=>{level=n;renderBands()};node.append(b)}$('#count').textContent=`${level} 分目标 · ${words.filter(w=>w.level===level).length} 个词 · ${sentences.filter(s=>s.level===level).length} 个句子`}
function adaptiveQuestion(){const pool=words.filter(w=>w.level===currentLevel&&!used.has(w.word));const item=shuffle(pool)[0];used.add(item.word);return{item,choices:shuffle([item,...shuffle(words.filter(w=>w.word!==item.word)).slice(0,3)])}}
function start(which,review=false){stopAudio();mode=which;reviewing=review;position=0;score=0;history=[];used=new Set();currentLevel=level;answered=false;if(which==='syntax')round=shuffle(sentences.filter(s=>s.level===level)).map((item,index)=>({item,target:['predicate','connector','modifier'][index%3]}));else if(which==='adaptive')round=[adaptiveQuestion()];else round=makeRound(review?words.filter(w=>saved.includes(w.word)):words.filter(w=>w.level===level),mode);$('.setup').hidden=true;$('#game').hidden=false;$('#game-title').textContent=`${names[mode]} · ${review?'生词复习':level+' 分目标'}`;renderQuestion();$('#game').scrollIntoView({behavior:'smooth',block:'start'})}
function renderQuestion(){answered=false;$('#next').hidden=true;$('#feedback').replaceChildren();$('#question').replaceChildren();$('#audio-status').textContent='';const total=mode==='adaptive'?12:round.length;$('#position').textContent=`${position+1} / ${total}${mode==='adaptive'?' · 当前难度 '+currentLevel+' 分目标':''}`;$('#score').textContent=`答对 ${score} 题`;$('#progress-bar').style.width=`${position/total*100}%`;const {item}=round[position];const q=$('#question');if(mode==='syntax'){const target=round[position].target;const labels={predicate:'主句完整谓语',connector:'连接词',modifier:'句首修饰成分'};q.innerHTML=`<p class="note">原创雅思风格教学例句 · ${level} 分目标组</p><h3>找出${labels[target]}</h3><p class="note">点击句中的一块。谓语只看主句，包含助动词、情态动词和否定词；从句内部的谓语不在本题选择范围。</p>`;const chunks=document.createElement('div');chunks.className='sentence-chunks';item.chunks.forEach((text,index)=>{const b=document.createElement('button');b.textContent=text;b.onclick=()=>checkSyntax(index,b);chunks.append(b)});q.append(chunks);return}
if(mode==='spelling'){q.innerHTML=`<p class="note">根据中文含义写出英文单词。</p><h3>${item.meaning}</h3><p class="note">${item.word.length} 个字母</p><form class="answer-form"><input aria-label="英文拼写" autocomplete="off" autocapitalize="none" spellcheck="false" required><button class="primary" type="submit">提交答案</button></form>`;q.querySelector('form').onsubmit=e=>{e.preventDefault();const input=q.querySelector('input');const correct=normalize(input.value)===item.word;if(!normalize(input.value))return;finishAnswer(correct,input.value);input.disabled=true;q.querySelector('button[type=submit]').disabled=true};q.querySelector('input').focus();return}
if(mode==='sound'){q.innerHTML='<p class="note">点击播放，选择你听到的单词。作答后查看词义，并跟读两遍。</p><h3>听音辨词</h3><p class="note">这是听辨与跟读练习，不会录音或评判你的发音。</p>';const controls=document.createElement('div');controls.className='audio-controls';controls.append(audioButton(item.word,'▶ 播放发音'),audioButton(item.word,'慢速播放',true));q.append(controls)}else q.innerHTML=`<p class="note">选择这个单词的中文含义。</p><h3>${item.word}</h3>`;
const choices=document.createElement('div');choices.className='choices';round[position].choices.forEach(w=>{const b=document.createElement('button');b.textContent=mode==='sound'?w.word:w.meaning;b.onclick=()=>{if(answered)return;choices.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add(w.word===item.word?'correct':'incorrect');finishAnswer(w.word===item.word,b.textContent)};choices.append(b)});q.append(choices)}
function checkSyntax(index,button){if(answered)return;const{item,target}=round[position];const correct=item.roles[index]===target;$('#question').querySelectorAll('button').forEach(b=>b.disabled=true);button.classList.add(correct?'correct':'incorrect');answered=true;if(correct)score++;history.push({item,correct});$('#feedback').innerHTML=`<p class="${correct?'':'wrong'}">${correct?'答对了 ✓':'再看一下结构'} · ${item.explanation}</p><div class="structure"><p>主句谓语：<strong>${item.chunks[2]}</strong></p><p>连接词：<strong>${item.chunks[4]}</strong></p><p>句首修饰成分：<strong>${item.chunks[0]}</strong></p></div>`;showNext()}
function finishAnswer(correct,response){if(answered)return;answered=true;if(correct)score++;const item=round[position].item;history.push({item,correct,response});if(!correct)add(item.word);$('#feedback').innerHTML=`<p class="${correct?'':'wrong'}">${correct?'答对了 ✓':'本题已加入生词本'} · <strong>${item.word}</strong> — ${item.meaning}</p>`;const controls=document.createElement('div');controls.className='audio-controls';controls.append(audioButton(item.word,'听发音 / 跟读'));const save=document.createElement('button');save.className='quiet';save.textContent=saved.includes(item.word)?'已在生词本':'加入生词本';save.onclick=()=>{add(item.word);save.textContent='已在生词本'};controls.append(save);$('#feedback').append(controls);showNext()}
function showNext(){$('#score').textContent=`答对 ${score} 题`;$('#next').hidden=false;$('#next').textContent=position+1===(mode==='adaptive'?12:round.length)?'查看本轮结果 →':'下一题 →'}
function finish(){stopAudio();$('#next').hidden=true;$('#feedback').replaceChildren();$('#progress-bar').style.width='100%';const q=$('#question');q.replaceChildren();q.innerHTML=`<h3>本轮完成</h3><div class="result-score">${score}<small style="font:20px system-ui"> / ${history.length}</small></div>`;if(mode==='adaptive'){const suggested=Math.max(5,Math.min(9,currentLevel));q.innerHTML+=`<h3>建议从 ${suggested} 分目标组开始练习</h3><p class="note">本次 12 题随表现逐题调整：答对提高一组，答错降低一组，范围为 5–9。建议取最后一题作答后的难度。测试只覆盖本网站词义识别题库，不评估拼写、发音或整体阅读能力，也不预测雅思分数。</p>`;try{localStorage.setItem('silvia-placement',JSON.stringify({level:suggested,score,total:history.length,date:Date.now()}))}catch{}const practice=document.createElement('button');practice.className='primary';practice.textContent='按推荐目标开始练习';practice.onclick=()=>{level=suggested;exit()};q.append(practice)}const list=document.createElement('ul');list.className='results';for(const h of history){const li=document.createElement('li');li.textContent=mode==='syntax'?`${h.correct?'✓':'✕'} ${h.item.chunks.join(' ')}`:`${h.correct?'✓':'✕'} ${h.item.word} — ${h.item.meaning}（${h.item.level} 分目标组）`;list.append(li)}q.append(list);const again=document.createElement('button');again.className='quiet';again.textContent='再练一轮';again.onclick=()=>start(mode,reviewing);q.append(again);const back=document.createElement('button');back.className='quiet';back.textContent='选择其他练习';back.onclick=exit;q.append(back)}
function exit(){stopAudio();$('#game').hidden=true;$('.setup').hidden=false;renderBands();$('.setup').scrollIntoView({behavior:'smooth'})}
$('#next').onclick=()=>{stopAudio();if(mode==='adaptive'){const previous=history.at(-1);currentLevel=Math.max(5,Math.min(9,currentLevel+(previous.correct?1:-1)));if(position===11){finish();return}round.push(adaptiveQuestion())}else if(position===round.length-1){finish();return}position++;renderQuestion()};$('#exit').onclick=exit;$('#review').onclick=()=>start('meaning',true);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));if(!speechAvailable){$('#audio-note').textContent='当前浏览器不支持发音播放；请使用支持英语语音的浏览器进行听音练习。';document.querySelector('[data-mode=sound]').disabled=true}else $('#audio-note').textContent='发音使用设备的英语语音，首次使用请确认音量；不录音。';renderBands();renderSaved();
if(new URLSearchParams(location.search).get('mode')==='adaptive')start('adaptive');
