// Original teaching examples; not reproduced IELTS test passages.
const raw={
5:[['In many cities,','people','use','buses','because','they are affordable.','句首介词短语说明地点；use 是主句谓语；because 引出原因。'],['After school,','students','read','books','although','they sometimes feel tired.','After school 是时间修饰语；read 是主句谓语；although 表示让步。'],['In winter,','birds','move','to warmer places','when','food becomes scarce.','In winter 修饰时间；move 是主句谓语；when 引出时间条件。']],
6:[['According to the survey,','regular exercise','improves','mental health','because','it helps reduce stress.','According to the survey 是信息来源修饰语；improves 是主句谓语；because 引出原因。'],['Over the past decade,','online learning','has changed','access to education','while','traditional classrooms remain important.','时间短语修饰主句；has changed 是完整谓语（助动词＋过去分词）；while 表示对照。'],['In rural areas,','local communities','can benefit','from better transport','if','services are reliable.','地点短语是修饰成分；can benefit 包含情态动词；if 引出条件。']],
7:[['Despite the initial cost,','renewable energy','offers','long-term benefits','although','storage remains a challenge.','Despite 后接名词短语，整体作让步修饰语；offers 是主句谓语；although 连接让步从句。'],['Under controlled conditions,','the researchers','observed','a significant increase in plant growth','whereas','the untreated group showed little change.','句首短语说明实验条件；observed 为主句谓语；whereas 连接对比信息。'],['With limited funding,','the project','was postponed','until the following year','because','additional resources were required.','With 短语说明背景；was postponed 是被动谓语；because 引出原因。']],
8:[['In light of the available evidence,','the proposed explanation','appears','inadequate','although','it accounts for some observations.','句首短语提供判断依据；appears 为主句系动词谓语；although 引出让步。'],['Irrespective of individual preferences,','environmental policies','must address','the cumulative effects of consumption','since','these extend beyond national borders.','Irrespective of 短语修饰适用范围；must address 是主句谓语；since 在此表示原因。'],['Contrary to earlier assumptions,','the relationship between the variables','has proved','more complex than expected','while','the underlying mechanism remains unclear.','Contrary to 短语作对照修饰语；has proved 为主句完整谓语；while 连接对照分句。']],
9:[['Notwithstanding methodological limitations,','the convergence of independent findings','provides','compelling support for the hypothesis','insofar as','alternative explanations have been systematically excluded.','Notwithstanding 短语作让步修饰语；provides 为主句谓语；insofar as 限定判断成立的程度或范围。'],['Against a backdrop of unprecedented ecological change,','the persistence of these communities','may be attributed','to their capacity for rapid adaptation','provided that','critical thresholds are not exceeded.','句首背景短语修饰主句；may be attributed 是情态被动谓语；provided that 引出条件。'],['In the absence of corroborating evidence,','the ostensibly plausible interpretation','cannot be regarded','as incontrovertible','even though','it is consistent with the prevailing paradigm.','句首短语说明证据条件；cannot be regarded 是完整主句谓语；even though 引出让步。']]
};
export const sentences=Object.entries(raw).flatMap(([level,rows])=>rows.map((r,index)=>({id:`s${level}-${index}`,level:Number(level),chunks:r.slice(0,6),roles:['modifier','subject','predicate','object','connector','clause'],explanation:r[6]})));
